name: 'olist_project'
version: '1.0.0'
profile: 'olist_project'

model-paths: ["models"]

models:
  olist_project:
    bronze:
      +materialized: view
      +schema: bronze
    silver:
      +materialized: table
      +schema: silver
    gold:
      +materialized: table
      +schema: gold